### ISSUE TITLE
Getting syntax error in minhash.py

### ISSUE THREAD

**Issue by duesXMachine** [justinnbt/SnaPy#23]
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from snapy import MinHash, LSH
  File "/home/user/venvs/project/lib/python3.5/site-packages/snapy/__init__.py", line 2, in <module>
    from .minhash import MinHash
  File "/home/user/venvs/project/lib/python3.5/site-packages/snapy/minhash.py", line 73
    low=1, high=100_000_000, size=permutations
                          ^
SyntaxError: invalid syntax
```
I got this error while testing LSH

**Comment by justinnbt** [comment]
Hi duesXMachine, thanks for raising this issue and submitting a pull request. I have merged your changes to master and will include them in the next release.
